"""
Export Routes - Document Exports (DOCX & PDF)
=============================================
Proposal export to Microsoft Word and PDF formats.
"""

import io
from datetime import datetime

import structlog
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select

from app.api.deps import UserAuth, get_current_user, get_user_policy_role
from app.database import get_session
from app.models.proposal import Proposal, ProposalSection
from app.models.rfp import RFP
from app.services.audit_service import log_audit_event
from app.services.policy_engine import PolicyAction, evaluate

from .helpers import enforce_export_policy, has_html, render_html_to_docx

logger = structlog.get_logger(__name__)

router = APIRouter()


def create_docx_proposal(
    proposal: Proposal,
    sections: list[ProposalSection],
    rfp: RFP,
) -> bytes:
    """Generate a DOCX file from proposal sections."""
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="python-docx not installed. Run: pip install python-docx",
        )

    doc = Document()
    doc.core_properties.title = proposal.title
    doc.core_properties.author = "RFP Sniper"
    doc.core_properties.created = datetime.utcnow()

    title = doc.add_heading(proposal.title, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    details = doc.add_paragraph()
    details.add_run("Solicitation Number: ").bold = True
    details.add_run(rfp.solicitation_number)
    details.add_run("\n")
    details.add_run("Agency: ").bold = True
    details.add_run(rfp.agency)
    details.add_run("\n")
    if rfp.response_deadline:
        details.add_run("Due Date: ").bold = True
        details.add_run(rfp.response_deadline.strftime("%B %d, %Y"))

    doc.add_page_break()

    doc.add_heading("Table of Contents", 1)
    doc.add_paragraph("(Update field to generate TOC)")
    doc.add_page_break()

    if proposal.executive_summary:
        doc.add_heading("Executive Summary", 1)
        doc.add_paragraph(proposal.executive_summary)
        doc.add_page_break()

    for section in sorted(sections, key=lambda s: s.display_order):
        doc.add_heading(f"{section.section_number}. {section.title}", 2)

        if section.requirement_text:
            req_para = doc.add_paragraph()
            req_para.add_run("Requirement: ").bold = True
            req_para.add_run(section.requirement_text[:500])
            if len(section.requirement_text) > 500:
                req_para.add_run("...")
            doc.add_paragraph()

        content = section.final_content
        if not content and section.generated_content:
            content = section.generated_content.get("clean_text", "")

        if content:
            render_html_to_docx(doc, content)
        else:
            doc.add_paragraph("[Section content pending]")

        doc.add_paragraph()

    doc.add_page_break()
    footer = doc.add_paragraph()
    footer.add_run("Generated by RFP Sniper").italic = True
    footer.add_run(f" on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    return buffer.getvalue()


def create_pdf_proposal(
    proposal: Proposal,
    sections: list[ProposalSection],
    rfp: RFP,
) -> bytes:
    """Generate a PDF file from proposal sections using weasyprint."""
    try:
        from weasyprint import HTML
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="weasyprint not installed. Run: pip install weasyprint",
        )

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            @page {{
                size: letter;
                margin: 1in;
                @bottom-center {{
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 10pt;
                    color: #666;
                }}
            }}
            body {{
                font-family: 'Georgia', serif;
                font-size: 12pt;
                line-height: 1.6;
                color: #333;
            }}
            h1 {{
                font-size: 24pt;
                text-align: center;
                margin-bottom: 0.5in;
                color: #1a1a1a;
            }}
            h2 {{
                font-size: 16pt;
                border-bottom: 2px solid #333;
                padding-bottom: 5pt;
                margin-top: 0.5in;
            }}
            .title-page {{
                text-align: center;
                page-break-after: always;
            }}
            .details {{
                margin: 1in auto;
                width: 80%;
            }}
            .details p {{
                margin: 0.2in 0;
            }}
            .requirement {{
                background: #f5f5f5;
                padding: 10pt;
                border-left: 3px solid #666;
                margin: 10pt 0;
                font-style: italic;
            }}
            .section-content {{
                margin: 0.2in 0;
            }}
            pre {{
                background: #f4f6fb;
                border: 1px solid #d7deed;
                border-radius: 6px;
                padding: 10pt;
                font-family: 'Courier New', monospace;
                font-size: 10pt;
                white-space: pre-wrap;
            }}
            code {{
                font-family: 'Courier New', monospace;
            }}
            .footer {{
                margin-top: 1in;
                font-size: 10pt;
                color: #666;
                font-style: italic;
            }}
        </style>
    </head>
    <body>
        <div class="title-page">
            <h1>{proposal.title}</h1>
            <div class="details">
                <p><strong>Solicitation Number:</strong> {rfp.solicitation_number}</p>
                <p><strong>Agency:</strong> {rfp.agency}</p>
                <p><strong>Due Date:</strong> {rfp.response_deadline.strftime("%B %d, %Y") if rfp.response_deadline else "TBD"}</p>
            </div>
        </div>
    """

    if proposal.executive_summary:
        html_content += f"""
        <h2>Executive Summary</h2>
        <div class="section-content">
            {proposal.executive_summary.replace(chr(10), "<br>")}
        </div>
        """

    for section in sorted(sections, key=lambda s: s.display_order):
        html_content += f"""
        <h2>{section.section_number}. {section.title}</h2>
        """

        if section.requirement_text:
            html_content += f"""
            <div class="requirement">
                <strong>Requirement:</strong> {section.requirement_text[:500]}{"..." if len(section.requirement_text) > 500 else ""}
            </div>
            """

        content = section.final_content
        if not content and section.generated_content:
            content = section.generated_content.get("clean_text", "")

        if content:
            if has_html(content):
                html_content += f'<div class="section-content">{content}</div>'
            else:
                paragraphs = content.split("\n\n")
                for para in paragraphs:
                    if para.strip():
                        html_content += f"<p>{para.strip()}</p>"
        else:
            html_content += "<p><em>[Section content pending]</em></p>"

    html_content += f"""
        <div class="footer">
            Generated by RFP Sniper on {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
        </div>
    </body>
    </html>
    """

    pdf_bytes = HTML(string=html_content).write_pdf()

    return pdf_bytes


@router.get("/proposals/{proposal_id}/docx")
async def export_proposal_docx(
    proposal_id: int,
    request: Request,
    current_user: UserAuth = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """Export a proposal to Microsoft Word (DOCX) format."""
    result = await session.execute(
        select(Proposal).where(
            Proposal.id == proposal_id,
            Proposal.user_id == current_user.id,
        )
    )
    proposal = result.scalar_one_or_none()

    if not proposal:
        raise HTTPException(status_code=404, detail="Proposal not found")

    user_role = await get_user_policy_role(current_user.id, session)
    policy = evaluate(PolicyAction.EXPORT, proposal.classification, user_role)
    await log_audit_event(
        session,
        user_id=current_user.id,
        entity_type="proposal",
        entity_id=proposal_id,
        action="export_docx",
        metadata=policy.to_audit_dict(),
    )
    await enforce_export_policy(
        policy=policy,
        current_user=current_user,
        session=session,
        request=request,
    )

    sections_result = await session.execute(
        select(ProposalSection)
        .where(ProposalSection.proposal_id == proposal_id)
        .order_by(ProposalSection.display_order)
    )
    sections = list(sections_result.scalars().all())

    rfp_result = await session.execute(select(RFP).where(RFP.id == proposal.rfp_id))
    rfp = rfp_result.scalar_one_or_none()

    if not rfp:
        raise HTTPException(status_code=404, detail="Associated RFP not found")

    try:
        docx_bytes = create_docx_proposal(proposal, sections, rfp)
    except Exception as e:
        logger.error(f"DOCX generation failed: {e}")
        raise HTTPException(status_code=500, detail=f"Export failed: {str(e)}")

    await session.commit()

    safe_title = "".join(c for c in proposal.title[:50] if c.isalnum() or c in " -_")
    filename = f"{safe_title}_{datetime.utcnow().strftime('%Y%m%d')}.docx"

    return StreamingResponse(
        io.BytesIO(docx_bytes),
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/proposals/{proposal_id}/pdf")
async def export_proposal_pdf(
    proposal_id: int,
    request: Request,
    current_user: UserAuth = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """Export a proposal to PDF format."""
    result = await session.execute(
        select(Proposal).where(
            Proposal.id == proposal_id,
            Proposal.user_id == current_user.id,
        )
    )
    proposal = result.scalar_one_or_none()

    if not proposal:
        raise HTTPException(status_code=404, detail="Proposal not found")

    user_role = await get_user_policy_role(current_user.id, session)
    policy = evaluate(PolicyAction.EXPORT, proposal.classification, user_role)
    await log_audit_event(
        session,
        user_id=current_user.id,
        entity_type="proposal",
        entity_id=proposal_id,
        action="export_pdf",
        metadata=policy.to_audit_dict(),
    )
    await enforce_export_policy(
        policy=policy,
        current_user=current_user,
        session=session,
        request=request,
    )

    sections_result = await session.execute(
        select(ProposalSection)
        .where(ProposalSection.proposal_id == proposal_id)
        .order_by(ProposalSection.display_order)
    )
    sections = list(sections_result.scalars().all())

    rfp_result = await session.execute(select(RFP).where(RFP.id == proposal.rfp_id))
    rfp = rfp_result.scalar_one_or_none()

    if not rfp:
        raise HTTPException(status_code=404, detail="Associated RFP not found")

    try:
        pdf_bytes = create_pdf_proposal(proposal, sections, rfp)
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        raise HTTPException(status_code=500, detail=f"Export failed: {str(e)}")

    await session.commit()

    safe_title = "".join(c for c in proposal.title[:50] if c.isalnum() or c in " -_")
    filename = f"{safe_title}_{datetime.utcnow().strftime('%Y%m%d')}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
